const programCards = [
  {
    id: 'bsc',
    category: 'ug',
    title: 'Bachelor of Science (B.Sc.)',
    icon: 'fa-flask',
    badge: '6 Semesters \u2022 UG Degree',
    description: 'Comprehensive undergraduate science programs covering Yoga, IT, Computer Science, PCB, PCM, Microbiology, and Food Nutrition & Dietetics with hands-on laboratory training.',
    eligibility: '10+2 with Science (PCM/PCB)',
    feePerSem: '\u20b910,000',
    totalFee: '\u20b960,000',
    specializations: ['Yoga', 'I.T.', 'C.S.', 'P.C.B.', 'P.C.M.', 'Microbiology', 'Food Nutrition & Dietetics'],
    pageLink: 'programs/bsc/index.html'
  },
  {
    id: 'ba',
    category: 'ug',
    title: 'Bachelor of Arts (B.A.)',
    icon: 'fa-book-open',
    badge: '6 Semesters \u2022 UG Degree',
    description: 'Arts programs integrating holistic education with modern disciplines including Yoga Studies & Sports, Sanskrit, Philosophy, Psychology, and more.',
    eligibility: '10+2 in any stream',
    feePerSem: '\u20b98,000 - \u20b910,000',
    totalFee: '\u20b948,000 - \u20b960,000',
    specializations: ['General', 'Yoga Studies & Sports'],
    pageLink: 'programs/ba/index.html'
  },
  {
    id: 'bcom',
    category: 'ug',
    title: 'Bachelor of Commerce (B.Com)',
    icon: 'fa-chart-line',
    badge: '6 Semesters \u2022 UG Degree',
    description: 'Commerce education blending accounting, business economics, and financial management with value-based learning approach.',
    eligibility: '10+2 in any stream',
    feePerSem: '\u20b910,000',
    totalFee: '\u20b960,000',
    specializations: ['Commerce'],
    pageLink: null
  },
  {
    id: 'bca',
    category: 'ug',
    title: 'Bachelor of Computer Application (B.C.A.)',
    icon: 'fa-laptop-code',
    badge: '6 Semesters \u2022 UG Degree',
    description: 'Comprehensive computer applications program covering software development, programming languages, database management, and web technologies.',
    eligibility: '10+2 in any stream',
    feePerSem: '\u20b910,000',
    totalFee: '\u20b960,000',
    specializations: ['Computer Application'],
    pageLink: null
  },
  {
    id: 'bba',
    category: 'ug',
    title: 'Bachelor of Business Administration (B.B.A.)',
    icon: 'fa-briefcase',
    badge: '6 Semesters \u2022 UG Degree',
    description: 'Management education focused on ethical leadership, sustainable enterprise, and practical business skills for tomorrow\'s entrepreneurs.',
    eligibility: '10+2 in any stream',
    feePerSem: '\u20b910,000',
    totalFee: '\u20b960,000',
    specializations: ['Business Administration'],
    pageLink: null
  },
  {
    id: 'btech',
    category: 'ug',
    title: 'Bachelor of Technology (B.Tech.)',
    icon: 'fa-cogs',
    badge: '8 Semesters \u2022 UG Degree',
    description: 'Engineering programs in Electrical, Computer Science, Civil, Mining, Chemical, Electronics & Telecommunication with practical lab training.',
    eligibility: '10+2 with PCM (50% marks)',
    feePerSem: '\u20b920,000',
    totalFee: '\u20b91,60,000',
    specializations: ['Electrical', 'Computer Science', 'Electrical & Electronics', 'Mining', 'Civil', 'Chemical Engineering', 'Electronics & Tele-Communication', 'Electronics Engineering', 'Environmental Science'],
    pageLink: 'programs/btech/index.html'
  },
  {
    id: 'bsw',
    category: 'ug',
    title: 'Bachelor of Social Work (B.S.W.)',
    icon: 'fa-hands-helping',
    badge: '6 Semesters \u2022 UG Degree',
    description: 'Social work education focusing on community development, rural outreach, and value-based social service with experiential learning.',
    eligibility: '10+2 in any stream',
    feePerSem: '\u20b910,000',
    totalFee: '\u20b960,000',
    specializations: ['Social Work'],
    pageLink: null
  },
  {
    id: 'bhm',
    category: 'ug',
    title: 'Bachelor of Hotel Management (B.H.M.)',
    icon: 'fa-hotel',
    badge: '8 Semesters \u2022 UG Degree',
    description: 'Hotel management program covering hospitality operations, food & beverage management, front office, and housekeeping with industry internships.',
    eligibility: '10+2 in any stream',
    feePerSem: '\u20b910,000',
    totalFee: '\u20b980,000',
    specializations: ['Hotel Management'],
    pageLink: null
  },
  {
    id: 'blib',
    category: 'ug',
    title: 'Bachelor of Library & Information Science',
    icon: 'fa-book',
    badge: '2 Semesters \u2022 UG Degree',
    description: 'Library science program covering digital library management, information organization, cataloguing, and knowledge management systems.',
    eligibility: 'Graduation in any discipline',
    feePerSem: '\u20b96,000',
    totalFee: '\u20b912,000',
    specializations: ['Library & Information Science'],
    pageLink: null
  },
  {
    id: 'msc',
    category: 'pg',
    title: 'Master of Science (M.Sc.)',
    icon: 'fa-microscope',
    badge: '4 Semesters \u2022 PG Degree',
    description: 'Postgraduate science programs with 27+ specializations spanning Physics, Chemistry, Botany, Mathematics, Zoology, Biotechnology, Nanotechnology, and more.',
    eligibility: 'B.Sc. in relevant subject',
    feePerSem: '\u20b918,000',
    totalFee: '\u20b972,000',
    specializations: ['Physics', 'Chemistry', 'Botany', 'Mathematics', 'Zoology', 'Statistics', 'Electronics', 'Bio-Chemistry', 'Bio-Science', 'Bio-Physics', 'Bio-Technology', 'Anthropology', 'Criminology & Forensic', 'Microbiology', 'Forestry & Wildlife', 'CS & IT', 'Nanotechnology', 'Environmental Science', 'Food Science & Nutrition', 'Yoga & Nephropathy', 'Computer Application', 'Home Science', 'Geography', 'Nutrition Exercise & Sports', 'Library Science', 'Biological Science', 'Astronomy', 'Neuroscience', 'Cell Biology & Genetic', 'Plant Science', 'Soil Science', 'Material Science'],
    pageLink: 'programs/msc/index.html'
  },
  {
    id: 'msc-nutrition',
    category: 'pg',
    title: 'M.Sc. Food Nutrition & Dietetics',
    icon: 'fa-leaf',
    badge: '4 Semesters \u2022 PG Degree',
    description: 'Specialized postgraduate program in food nutrition, dietetics, and dietary management with focus on community nutrition and clinical dietetics.',
    eligibility: 'B.Sc. in Food Nutrition / Home Science',
    feePerSem: '\u20b918,000',
    totalFee: '\u20b972,000',
    specializations: ['Food Nutrition & Dietetics'],
    pageLink: null
  },
  {
    id: 'ma',
    category: 'pg',
    title: 'Master of Arts (M.A.)',
    icon: 'fa-pen-fancy',
    badge: '4 Semesters \u2022 PG Degree',
    description: 'Postgraduate arts programs with 15+ specializations in English, Hindi, Sanskrit, Philosophy, History, Psychology, Sociology, and more.',
    eligibility: 'B.A. in relevant subject',
    feePerSem: '\u20b912,000',
    totalFee: '\u20b948,000',
    specializations: ['English', 'Hindi', 'Sanskrit', 'Philosophy', 'History', 'Political Science', 'Geography', 'Psychology', 'Sociology', 'Social Work', 'Journalism & Mass Communication', 'Library Science', 'Yoga Studies & Sports', 'Education', 'Fashion Design'],
    pageLink: 'programs/ma/index.html'
  },
  {
    id: 'mcom',
    category: 'pg',
    title: 'Master of Commerce (M.Com)',
    icon: 'fa-coins',
    badge: '4 Semesters \u2022 PG Degree',
    description: 'Postgraduate commerce programs covering accounting, auditing, taxation, banking, e-commerce, and business management.',
    eligibility: 'B.Com. or equivalent',
    feePerSem: '\u20b914,000',
    totalFee: '\u20b956,000',
    specializations: ['Accounting & Auditing', 'Business Economics', 'Business Management', 'Taxation', 'Financial Accounting', 'Banking', 'Computer Application Banking & Finance', 'Cost Accounting', 'E-Commerce', 'Banking & Insurance', 'Management Accounting', 'Commerce', 'Business Mathematics'],
    pageLink: null
  },
  {
    id: 'mba',
    category: 'pg',
    title: 'Master of Business Administration (M.B.A.)',
    icon: 'fa-building',
    badge: '4 Semesters \u2022 PG Degree',
    description: 'MBA with 21 specializations covering Business Management, HR, Finance, Marketing, Hospital Management, Digital Marketing, and more.',
    eligibility: 'Graduation in any discipline',
    feePerSem: '\u20b925,000',
    totalFee: '\u20b91,00,000',
    specializations: ['Business Management', 'Rural Management', 'Security & Portfolio Management', 'Hospital Management', 'Financial Management', 'Food Service Management', 'Hotel Management & Catering Technology', 'Event Management', 'Industrial Management', 'Hospitality Management', 'Disaster Management', 'Marketing & Sales Management', 'Export Management', 'Advertising Management', 'Foreign Trade Management', 'Production Management', 'Travel & Tourism Management', 'Human Resource Management', 'Retail Trade Management', 'Digital Marketing Management', 'Banking Management'],
    pageLink: 'programs/mba/index.html'
  },
  {
    id: 'mca',
    category: 'pg',
    title: 'Master of Computer Application (M.C.A.)',
    icon: 'fa-laptop',
    badge: '4 Semesters \u2022 PG Degree',
    description: 'Advanced computer applications program covering software engineering, database systems, web technologies, and emerging tech trends.',
    eligibility: 'BCA / B.Sc. IT / Graduation with Maths',
    feePerSem: '\u20b925,000',
    totalFee: '\u20b91,00,000',
    specializations: ['Computer Application'],
    pageLink: null
  },
  {
    id: 'msw',
    category: 'pg',
    title: 'Master of Social Work (M.S.W.)',
    icon: 'fa-people-carry',
    badge: '4 Semesters \u2022 PG Degree',
    description: 'Postgraduate social work program focusing on community development, social policy, and professional social work practice.',
    eligibility: 'B.S.W. / B.A. / B.Sc. in any stream',
    feePerSem: '\u20b912,000',
    totalFee: '\u20b948,000',
    specializations: ['Social Work'],
    pageLink: null
  },
  {
    id: 'mlib',
    category: 'pg',
    title: 'Master of Library & Information Science',
    icon: 'fa-book-reader',
    badge: '2 Semesters \u2022 PG Degree',
    description: 'Advanced library science program covering digital libraries, information systems, knowledge management, and research methodologies.',
    eligibility: 'B.Lib. / B.L.I.Sc.',
    feePerSem: '\u20b97,500',
    totalFee: '\u20b915,000',
    specializations: ['Library & Information Science'],
    pageLink: null
  },
  {
    id: 'dca',
    category: 'diploma',
    title: 'Diploma in Computer Application (D.C.A.)',
    icon: 'fa-desktop',
    badge: '2 Semesters \u2022 Diploma',
    description: 'Short-term diploma in computer applications covering MS Office, internet basics, programming fundamentals, and database management.',
    eligibility: '10+2 in any stream',
    feePerSem: '\u20b96,000',
    totalFee: '\u20b912,000',
    specializations: ['Computer Application'],
    pageLink: null
  },
  {
    id: 'pgdca',
    category: 'diploma',
    title: 'Post Graduation Diploma in Computer Application (P.G.D.C.A.)',
    icon: 'fa-microchip',
    badge: '2 Semesters \u2022 PG Diploma',
    description: 'Advanced diploma in computer applications for graduates covering programming, web development, and system administration.',
    eligibility: 'Graduation in any discipline',
    feePerSem: '\u20b97,500',
    totalFee: '\u20b915,000',
    specializations: ['Computer Application'],
    pageLink: null
  },
  {
    id: 'dhm',
    category: 'diploma',
    title: 'Diploma in Hotel Management (D.H.M.)',
    icon: 'fa-utensils',
    badge: '4 Semesters \u2022 Diploma',
    description: 'Diploma program in hotel management covering food production, front office operations, housekeeping, and food & beverage service.',
    eligibility: '10+2 in any stream',
    feePerSem: '\u20b98,000 - \u20b990,000',
    totalFee: '\u20b932,000 - \u20b93,60,000',
    specializations: ['Hotel Management'],
    pageLink: null
  },
  {
    id: 'pgdbm',
    category: 'diploma',
    title: 'PG Diploma in Business Management (P.G.D.B.M.)',
    icon: 'fa-user-tie',
    badge: '2 Semesters \u2022 PG Diploma',
    description: 'Postgraduate diploma in business management for graduates focusing on management principles, marketing, and organizational behavior.',
    eligibility: 'Graduation in any discipline',
    feePerSem: '\u20b920,000',
    totalFee: '\u20b940,000',
    specializations: ['Business Management'],
    pageLink: null
  },
  {
    id: 'cert-life',
    category: 'cert',
    title: 'Certificate in Life Management & Bhagwat Gita',
    icon: 'fa-certificate',
    badge: '1 Semester \u2022 Certificate',
    description: 'Certificate program integrating life management skills with Bhagwat Gita wisdom for personal development and holistic living.',
    eligibility: '10+2 in any stream',
    feePerSem: '\u20b96,000',
    totalFee: '\u20b96,000',
    specializations: ['Life Management'],
    pageLink: null
  },
  {
    id: 'cert-yoga',
    category: 'cert',
    title: 'Certificate in Yoga & Science',
    icon: 'fa-spa',
    badge: '1 Semester \u2022 Certificate',
    description: 'Certificate course combining yoga practices with scientific understanding of health, wellness, and consciousness.',
    eligibility: '10+2 in any stream',
    feePerSem: '\u20b96,000',
    totalFee: '\u20b96,000',
    specializations: ['Yoga & Science'],
    pageLink: null
  },
  {
    id: 'cert-sanskrit',
    category: 'cert',
    title: 'Certificate in Sanskrit Language',
    icon: 'fa-language',
    badge: '1 Semester \u2022 Certificate',
    description: 'Certificate course in Sanskrit language covering grammar, literature, and Vedic texts for cultural and spiritual enrichment.',
    eligibility: '10+2 in any stream',
    feePerSem: '\u20b96,000',
    totalFee: '\u20b96,000',
    specializations: ['Sanskrit Language'],
    pageLink: null
  },
  {
    id: 'mphil',
    category: 'phd',
    title: 'Master of Philosophy (M.Phil.)',
    icon: 'fa-graduation-cap',
    badge: '1.5 Years \u2022 Research Degree',
    description: 'Pre-doctoral research program providing advanced training in research methodology and specialized subject knowledge.',
    eligibility: 'Post-Graduation with 55% marks',
    feePerSem: '\u20b950,000/yr',
    totalFee: '\u20b975,000',
    specializations: ['Research'],
    pageLink: null
  },
  {
    id: 'phd',
    category: 'phd',
    title: 'Doctor of Philosophy (Ph.D.)',
    icon: 'fa-user-graduate',
    badge: '3 Years \u2022 Doctoral Degree',
    description: 'Doctoral research programs across 18+ disciplines including Hindi, English, Geography, Physics, Chemistry, Biotechnology, Yoga, Education, and more.',
    eligibility: 'Post-Graduation with 55% marks + NET/SLET',
    feePerSem: '\u20b990,000/yr',
    totalFee: '\u20b92,70,000',
    specializations: ['Hindi', 'English', 'Geography', 'Sociology', 'Social Work', 'Management', 'Commerce', 'Mass Communication', 'Yoga', 'Education', 'Physics', 'Chemistry', 'Bio-Technology', 'Bio-Chemistry', 'Zoology', 'Mathematics', 'Botany', 'Arts', 'Science'],
    pageLink: 'programs/phd/index.html'
  }
];
